apiVersion: v1
kind: Pod
metadata:
  name: kubeode-registry  # 修改此处
  namespace: kube-system
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 114.114.114.114
  containers:
  - name: kubeode-registry  # 修改此处
    image: ghcr.io/szbjb/kubeode_registry:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: data-registry-k8s-io
      mountPath: /var/lib/registry
    ports:
    - containerPort: 443
      hostPort: 443
    - containerPort: 6000
      hostPort: 6000
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: false
  volumes:
  - name: data-registry-k8s-io
    hostPath:
      path: /usr/local/kubeode/package/offline/Images/data_registry
      type: DirectoryOrCreate
