version: 0.1
log:
  fields:
    service: registry
    environment: development
storage:
  cache:
    blobdescriptor: file
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5004
  headers:
    X-Content-Type-Options: [nosniff]
  secret: asecretforlocaldevelopment
  relativeurls: false
  tls:
    certificate: /certs/registry.k8s.io/domain.crt
    key: /certs/registry.k8s.io/domain.key
proxy:
  remoteurl: https://registry.k8s.io
compatibility:
    schema1:
        enabled: true